const lang = {
  en: {
    appTitle: "FarmConnect – Agriculture Portal",
    login: "Login",
    signup: "Signup",
    logout: "Logout",
    registerHere: "Register here",
    welcome: "Welcome",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone",
    role: "Role",
    farmer: "Farmer",
    vendor: "Vendor",

    farmerDashboard: "Farmer Dashboard",
    availableCrops: "Available Crop Prices",
    crop: "Crop",
    price: "Price",
    quantity: "Quantity",
    location: "Location",
    vendorName: "Vendor",
    contact: "Contact",

    vendorDashboard: "Vendor Dashboard",
    addCrop: "Add Crop Price",
    publish: "Publish Price",

    adminDashboard: "Admin Dashboard",
    vendorApproval: "Vendor Approval Panel",
    status: "Status",
    approved: "Approved",
    pending: "Pending",
    approve: "Approve Vendor",
  },

  mr: {
    appTitle: "FarmConnect – कृषी पोर्टल",
    login: "लॉगिन",
    signup: "नोंदणी",
    logout: "लॉगआउट",
    registerHere: "येथे नोंदणी करा",
    welcome: "स्वागत आहे",
    email: "ईमेल",
    password: "पासवर्ड",
    name: "नाव",
    phone: "मोबाईल क्रमांक",
    role: "भूमिका",
    farmer: "शेतकरी",
    vendor: "व्यापारी",

    farmerDashboard: "शेतकरी डॅशबोर्ड",
    availableCrops: "उपलब्ध पिकांचे दर",
    crop: "पीक",
    price: "दर",
    quantity: "प्रमाण",
    location: "ठिकाण",
    vendorName: "व्यापारी",
    contact: "संपर्क",

    vendorDashboard: "व्यापारी डॅशबोर्ड",
    addCrop: "पीक दर जोडा",
    publish: "दर प्रकाशित करा",

    adminDashboard: "प्रशासक डॅशबोर्ड",
    vendorApproval: "व्यापारी मान्यता पॅनल",
    status: "स्थिती",
    approved: "मान्य",
    pending: "प्रलंबित",
    approve: "मान्यता द्या",
  },
};

export default lang;
